name: MACD Signal Daily Runner

on:
  schedule:
    # Test: Runs every minute for testing (change back to daily after testing)
    - cron: '* * * * *'
    # Uncomment below for daily at 11:15 AM UTC after testing
    # - cron: '15 11 * * *'
  
  # Allow manual triggering of the workflow
  workflow_dispatch:

# Grant permissions to write to the repository
permissions:
  contents: write

jobs:
  run-macd-signal:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Create data directory
      run: mkdir -p data
    
    - name: Run MACD Signal Script
      env:
        # Add your Telegram bot token as a GitHub secret
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_IDS: ${{ secrets.TELEGRAM_CHAT_IDS }}
      run: python main.py
    
    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add -A
        git diff --staged --quiet || git commit -m "Update stock data - $(date)"
        git push 