name: Portfolio MACD Daily (Kathmandu 11:00)

on:
  schedule:
    # 11:00 Asia/Kathmandu = 05:15 UTC
    - cron: "15 5 * * *"
  workflow_dispatch: {}

jobs:
  run-once:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run analysis once for previous Kathmandu day
        env:
          # Optional runtime toggles
          RUN_ONCE_NOW: "1"
        run: |
          python main.py --now
