name: Test Workflow

on:
  schedule:
    - cron: '*/2 * * * *'  # Every 2 minutes
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Simple test
      run: |
        echo "GitHub Actions is working!"
        date 